version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gfs
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        #- postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chunck1:
    build:
      context: chunk_server
      dockerfile: Dockerfile
      args:
        - APP_PORT=8080
    image: chunck_server
    restart: always
    ports:
      - "8080:8080"
    environment:
      STORAGE_PATH: data

  chunck2:
    image: chunck_server
    restart: always
    depends_on:
      - chunck1
    ports:
      - "8081:8081"
    environment:
      STORAGE_PATH: data
      ENV_PORT: 8081

  chunck3:
    image: chunck_server
    restart: always
    depends_on:
      - chunck1
    ports:
      - "8082:8082"
    environment:
      STORAGE_PATH: data
      ENV_PORT: 8082

  manager:
    image: chunks_manager
    build:
      context: main_server
      dockerfile: Dockerfile
      args:
        - APP_PORT=8020
    restart: always
    depends_on:
      - chunck1
      - chunck2
      - chunck3
    ports:
      - "8020:8020"
    environment:
      CHUNKS_PORTS: chunck1:8080;chunck2:8081;chunck3:8082
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gfs
      DB_USER: admin
      DB_PASSWORD: 1234

#volumes:
# postgres_data:
